### ISSUE TITLE
problem of running

### ISSUE THREAD

**Issue by hajar-co** [TijClass/Anonymous_Booking_website#13]
salut, c'est quoi le poblème quand je clique sur le code (localhosot/Anonymos...) il affiche ce message:

Warning: require(C:\xampp\htdocs\Anonymous_Booking_website\Codes/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Anonymous_Booking_website\Codes\index.php on line 6

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\Anonymous_Booking_website\Codes/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Anonymous_Booking_website\Codes\index.php on line 6

**Comment by abdelazizbardich** [comment]
Vous devez télécharger les dépendances en utilisant composer:
- comment installer [composer](https://www.youtube.com/watch?v=BGyuKpfMB9E)
- Puis accédez au dossier (Codes) a travers un terminal, où se trouve le fichier composer .json.
et tapez la commande ` composer update ` pour mettre à jour les packages requis.
