### ISSUE TITLE
verify front_end 

### ISSUE THREAD

**Issue by hajar-co** [TijClass/Anonymous_Booking_website#15]
salut, les amis  veuillez vérifier ma partie " html"
Merci d'avance!

**Comment by abdelazizbardich** [comment]
Si vous avez fini votre tache, vous devez créer une pull request et assigner un reviewer pour la verification

**Comment by hajar-co** [comment]
Merci pour votre réponse,
mais avant de faire un pull request j'attend toujours votre opinion et si il ya quelque chose à le modifier.

**Comment by abdelazizbardich** [comment]
Tout va bien, juste une modification: 
- Si vous ajoutez le code de `<html>` à `<body>` dans le fichier header.view.php ce sera bien, pour éviter la répétition du code da la partie header dans les deux pages (home et contact).
